name: Docker Build and Push

on:
  push:
    branches: [master]   
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Lägg till i [ditt repo] > Settings > Secrets and variables > Actions, OBS: Namnet till trots ska det vara din email
          password: ${{ secrets.DOCKER_PASSWORD }} # Lägg till i [ditt repo] > Settings > Secrets and variables > Actions

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .   
          file: ./Microservices.API/Dockerfile  
          push: true   
          tags: owlwood/recipeservice:latest  #Byt ut owlwood mot ert Docker-username, byt ut recipeservice mot namnet på er service
